// svelte/src/ToastStack.svelte
<script lang="ts">
  import ToastItem from "./ToastItem.svelte";
  import type { ToastMessage } from "./toast-types";
  type Props = { toasts: ToastMessage[]; onDismiss: (id: number) => void };
  let { toasts, onDismiss }: Props = $props();
</script>

{#if toasts.length}
  <div class="toast-stack" aria-live="polite" aria-relevant="additions">
    {#each toasts as toast (toast.id)}
      <ToastItem {toast} {onDismiss} />
    {/each}
  </div>
{/if}

// framework/src/ToastStack.tsx
import { useEffect } from "preact/hooks";

export type ToastMessage = {
  id: number;
  message: string;
};

function ToastItem(props: { toast: ToastMessage; onDismiss: (id: number) => void }) {
  useEffect(() => {
    const timer = window.setTimeout(() => props.onDismiss(props.toast.id), 2600);
    return () => window.clearTimeout(timer);
  }, [props.toast.id, props.onDismiss]);

  return (
    <button
      type="button"
      class="queued-toast show"
      title="Dismiss"
      onClick={() => props.onDismiss(props.toast.id)}
    >
      {props.toast.message}
    </button>
  );
}

export function ToastStack(props: { toasts: ToastMessage[]; onDismiss: (id: number) => void }) {
  if (!props.toasts.length) return null;
  return (
    <div class="toast-stack" aria-live="polite" aria-relevant="additions">
      {props.toasts.map((toast) => <ToastItem key={toast.id} toast={toast} onDismiss={props.onDismiss} />)}
    </div>
  );
}
