// solid/src/ToastStack.tsx
import { For, Show, createSignal, onCleanup, onMount } from "solid-js";

export type ToastMessage = {
  id: number;
  message: string;
};

function ToastItem(props: { toast: ToastMessage; onDismiss: (id: number) => void }) {
  const [leaving, setLeaving] = createSignal(false);
  let removalTimer: number | undefined;

  const dismiss = () => {
    if (leaving()) return;
    setLeaving(true);
    removalTimer = window.setTimeout(() => props.onDismiss(props.toast.id), 140);
  };

  let lifetimeTimer: number | undefined;
  onMount(() => {
    lifetimeTimer = window.setTimeout(dismiss, 2600);
  });
  onCleanup(() => {
    if (lifetimeTimer !== undefined) window.clearTimeout(lifetimeTimer);
    if (removalTimer !== undefined) window.clearTimeout(removalTimer);
  });

  return (
    <button
      type="button"
      class={`queued-toast show${leaving() ? " leaving" : ""}`}
      title="Dismiss"
      onClick={dismiss}
    >
      {props.toast.message}
    </button>
  );
}

export function ToastStack(props: { toasts: ToastMessage[]; onDismiss: (id: number) => void }) {
  return (
    <Show when={props.toasts.length}>
      <div class="toast-stack" aria-live="polite" aria-relevant="additions">
        <For each={props.toasts}>{(toast) => <ToastItem toast={toast} onDismiss={props.onDismiss} />}</For>
      </div>
    </Show>
  );
}

// framework/src/ToastStack.tsx
import { useEffect, useState } from "preact/hooks";

export type ToastMessage = {
  id: number;
  message: string;
};

function ToastItem(props: { toast: ToastMessage; onDismiss: (id: number) => void }) {
  const [leaving, setLeaving] = useState(false);

  const dismiss = () => {
    if (leaving) return;
    setLeaving(true);
    window.setTimeout(() => props.onDismiss(props.toast.id), 140);
  };

  useEffect(() => {
    const timer = window.setTimeout(dismiss, 2600);
    return () => window.clearTimeout(timer);
  }, [props.toast.id]);

  return (
    <button
      type="button"
      class={`queued-toast show${leaving ? " leaving" : ""}`}
      title="Dismiss"
      onClick={dismiss}
    >
      {props.toast.message}
    </button>
  );
}

export function ToastStack(props: { toasts: ToastMessage[]; onDismiss: (id: number) => void }) {
  if (!props.toasts.length) return null;
  return (
    <div class="toast-stack" aria-live="polite" aria-relevant="additions">
      {props.toasts.map((toast) => <ToastItem key={toast.id} toast={toast} onDismiss={props.onDismiss} />)}
    </div>
  );
}
